---
version: "3.8"

services:
  assets:
    build:
      context: .
      args:
        NPM_TOKEN: "${NPM_TOKEN}"
    container_name: client_fpwc_prod
    volumes:
      - .:/app:delegated
      - /app/node_modules
    ports:
      - "7778:7778"
    env_file:
      - .env
      - .env-prod
    init: true
    command: ["/usr/local/bin/npm", "run", "build"]

networks:
  default:
    external:
      name: lcl.fp.io